services:
  slipgate:
    build:
      context: ..
      dockerfile: deploy/slipgate/Dockerfile
    container_name: thefeed-slipgate
    restart: unless-stopped
    command:
      - "--listen=:53"
      - "--domain=${THEFEED_DOMAIN}"
      - "--upstream=thefeed:5300"
    ports:
      - "${SLIPGATE_BIND_IP:-0.0.0.0}:${SLIPGATE_HOST_PORT:-53}:53/udp"
    depends_on:
      - thefeed
    networks:
      - public_net
      - feed_net
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  thefeed:
    build:
      context: ..
      dockerfile: deploy/thefeed/Dockerfile
    container_name: thefeed-server
    restart: unless-stopped
    user: root
    env_file:
      - .env
    volumes:
      - ./state:/var/lib/thefeed:ro
      - feeddb_data:/feeddb
    command:
      - "--listen=:5300"
      - "--mode=no-telegram"
      - "--domain=${THEFEED_DOMAIN}"
      - "--compression=deflate"
      - "--padding-min=${DNS_PADDING_MIN}"
      - "--padding-max=${DNS_PADDING_MAX}"
      - "--max-dns-response-bytes=512"
      - "--disable-persistent-logs=true"
      - "--db=/feeddb/feed.db"
    expose:
      - "5300/udp"
    networks:
      - feed_net
      - public_net
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  authd:
    build:
      context: ..
      dockerfile: deploy/authd/Dockerfile
    container_name: thefeed-authd
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${AUTH_BIND_IP:-0.0.0.0}:${AUTH_HOST_PORT:-8443}:8443/tcp"
    volumes:
      - authd_data:/var/lib/thefeed
      - ./tls:/etc/thefeed/tls:ro
    command:
      - "--listen=:8443"
      - "--tls-cert=/etc/thefeed/tls/fullchain.pem"
      - "--tls-key=/etc/thefeed/tls/privkey.pem"
      - "--db=/var/lib/thefeed/tokens.db"
      - "--token-ttl-days=${TOKEN_TTL_DAYS}"
      - "--rate-limit-rps=${AUTH_RATE_LIMIT_RPS}"
      - "--disable-persistent-logs=true"
    networks:
      - public_net
      - feed_net
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    restart: unless-stopped
    environment:
      - TWITTER_AUTH_TOKEN=4668ee223bbf9f444700f2bbe2eb3557cd9fa9d2
      - TWITTER_CT0=806383153cff8a1f3e3e86fc41c69d4c50bd1e89093c5de04ce5f578a557df4319f45ae203a2b6dc50c7a32ff7d51c6a82f31cab636101cdc50f6b9468734a9261c230568f973efce80d7b85932548cb
    ports:
      - "1200:1200"
    networks:
      - feed_net
      - public_net

networks:
  feed_net:
    name: feed_net
    driver: bridge
    internal: true
  public_net:
    name: public_net
    driver: bridge

volumes:
  authd_data:
  feeddb_data:
